// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VotingAdminService.Data;

namespace VotingAdminService.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20201120111514_CreatingDb")]
    partial class CreatingDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("VotingAdminService.Models.Contender", b =>
                {
                    b.Property<int>("ContenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ContenderName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContenderId");

                    b.ToTable("Contenders");
                });
#pragma warning restore 612, 618
        }
    }
}
